Config = {}

Config.UseTarget = GetConvar('UseTarget', 'false') == 'true'

Config.PoliceOpen = true -- Can Police open all stashes

Config.Stashes = {
     ["stash1"] = {
         canAnyoneOpen = false,
         stashName = "stash1",
         coords = vector3(-262.76, -726.2, 125.47), 
         requirecid = false,
         jobrequired = false,
         gangrequired = true,
         gang = "dziadzio",
         job = "",
         cid = {""},  
         stashSize = 1250000,
         stashSlots = 125, 
     },
     ["pietras"] = {
        canAnyoneOpen = false,
        stashName = "pietras",
        coords = vector3(-3233.58, 813.61, 14.08),
        requirecid = false,
        jobrequired = false,
        gangrequired = true,
        gang = "pietras",
        job = "",
        cid = {""},  
        stashSize = 1250000,
        stashSlots = 125, 
    },
     ["ballas"] = {
        canAnyoneOpen = false,
        stashName = "ballas",
        coords = vector3(106.11, -1981.43, 20.96), 
        requirecid = false,
        jobrequired = false,
        gangrequired = true,
        gang = "ballas",
        job = "",
        cid = {""},  
        stashSize = 1250000,
        stashSlots = 125, 
    },
     ["Ochrona"] = {
        canAnyoneOpen = false,
        stashName = "Ochrona",
        coords = vector3(1236.62, -715.88, 60.7), 
        requirecid = false,
        jobrequired = true,
        gangrequired = false,
        gang = "",
        job = "ochrona",
        cid = {""},  
        stashSize = 1250000,
        stashSlots = 125, 
    },
     ["lsc"] = {
        canAnyoneOpen = false,
        stashName = "lsc",
        coords = vector3(42.71, 6467.14, 32.08), 
        requirecid = false,
        jobrequired = true,
        gangrequired = true,
        gang = "",
        job = "lsc",
        cid = {""},  
        stashSize = 1250000,
        stashSlots = 125, 
    },
    ["money"] = {
        canAnyoneOpen = false,
        stashName = "money",
        coords = vector3(106.1, 1211.27, 207.17), 
        requirecid = false,
        jobrequired = false,
        gangrequired = true,
        gang = "money",
        job = "",
        cid = {""},  
        stashSize = 1250000,
        stashSlots = 125, 
    },
    ["choinka"] = {
        canAnyoneOpen = false,
        stashName = "choinka",
        coords = vector3(-1123.79, 361.67, 71.31), 
        requirecid = false,
        jobrequired = true,
        gangrequired = true,
        gang = "choinka",
        job = "",
        cid = {""},  
        stashSize = 1250000,
        stashSlots = 125, 
    },
}
